title: Ethical Hacking
iconURL: assets/default-icon.png

# for a clean URL
permalink: :slug

social:
  github: SupunKavinda
  youtube: "Rincón hacker"
  instagram: rinconh4ck

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
